function figureFrameGreyHistogram(frameidx,results)

% data
Value = results.pixValue{results.frameIndex(frameidx)} ;
greyScaleValue = linspace(0,1,100);% [0:1:255]./255;
map = repmat(greyScaleValue',[1,3]);

nBarColors = length(greyScaleValue)-1;
% Create figure
figure1 = figure('Name','Histogram','Color',[1 1 1],'ToolBar','none','MenuBar','none');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.12 0.35 0.80 0.60]);
hold(axes1,'on');

for i = 1 : nBarColors
    histogram(Value,'Parent',axes1, 'BinEdges', [greyScaleValue(i) greyScaleValue(i+1)], 'DisplayStyle', 'bar', 'EdgeColor', 'none', 'FaceColor',map(i,:))%, 'BarWidth', 1);
end
xlim ([0 max(greyScaleValue)])
box(axes1,'on');
grid(axes1,'on');

% plot label
%%%%%%%%%%%%%%
% Create ylabel
ylabel('Pixel count','FontWeight','bold');

% Create xlabel
xlabel('grey level (a.u.)','FontWeight','bold');

% Create title
title('Histogram');

hold(axes1,'off');

% figure information
%%%%%%%%%%%%%%
% textbox
annotation(figure1,'textbox',[0.1 0.16 0.4 0.05],...
    'VerticalAlignment','middle',...
    'String',['Pixel count : ', num2str(results.nbPixel(results.frameIndex(frameidx)))],...
    'FontWeight','bold',...
    'FontSize',8,...
    'FontAngle','italic',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% textbox
annotation(figure1,'textbox',[0.1 0.11 0.4 0.05],...
    'VerticalAlignment','middle',...
    'String',['Mean value : ',num2str(round(results.meanValue(results.frameIndex(frameidx)),2)),' a.u.'],...
    'FontWeight','bold',...
    'FontSize',8,...
    'FontAngle','italic',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% textbox
annotation(figure1,'textbox',[0.1 0.06 0.4 0.05],...
    'VerticalAlignment','middle',...
    'String',['Standard deviation : ',num2str(round(results.stdValue(results.frameIndex(frameidx)),2)),' a.u.'],...
    'FontWeight','bold',...
    'FontSize',8,...
    'FontAngle','italic',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% textbox
annotation(figure1,'textbox',[0.5 0.16 0.4 0.05],...
    'VerticalAlignment','middle',...
    'String',['Max value : ',num2str(round(max(results.pixValue{results.frameIndex(frameidx)}),2)),' a.u.'],...
    'FontWeight','bold',...
    'FontSize',8,...
    'FontAngle','italic',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% textbox
annotation(figure1,'textbox',[0.5 0.11 0.4 0.05],...
    'VerticalAlignment','middle',...
    'String',['Min value : ',num2str(round(min(results.pixValue{results.frameIndex(frameidx)}),2)),' a.u.'],...
    'FontWeight','bold',...
    'FontSize',8,...
    'FontAngle','italic',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% textbox
annotation(figure1,'textbox',[0.5 0.06 0.4 0.05],...
    'VerticalAlignment','middle',...
    'String',['percent of void : ', num2str(round(results.voidPercent(results.frameIndex(frameidx)),2))],...
    'FontWeight','bold',...
    'FontSize',8,...
    'FontAngle','italic',...
    'FitBoxToText','off',...
    'EdgeColor','none');
end